<script setup lang="ts">
import { Page, Button, Badge, Card } from "ui"
import { name } from "./package.json"

useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }]
})
</script>

<template>
  <div class="space-y-6 p-8">
    <!-- Test heading with utilities -->
    <h1 class="mb-4 text-3xl font-bold text-blue-600">Tailwind v4 Test Page</h1>

    <!-- Test utility classes: padding, margin, spacing -->
    <div class="m-2 rounded-lg bg-gray-100 p-4">
      <h2 class="mb-2 text-xl font-semibold">Utility Classes Test</h2>
      <p class="py-2! px-4! rounded bg-white">Testing padding and margin utilities</p>
    </div>

    <!-- Test UI components from package -->
    <div class="space-y-4">
      <h2 class="text-xl font-semibold">UI Components from Package</h2>

      <!-- Buttons -->
      <div class="flex flex-wrap gap-4">
        <Button variant="primary" size="sm">Primary Small</Button>
        <Button variant="secondary" size="md">Secondary Medium</Button>
        <Button variant="outline" size="lg">Outline Large</Button>
        <Button variant="danger" :loading="true">Loading</Button>
      </div>

      <!-- Badges -->
      <div class="flex flex-wrap items-center gap-2">
        <Badge variant="primary">Primary</Badge>
        <Badge variant="success" size="sm">Success</Badge>
        <Badge variant="warning" size="md">Warning</Badge>
        <Badge variant="danger" size="lg">Danger</Badge>
        <Badge variant="info" :rounded="true">Info Pill</Badge>
      </div>

      <!-- Card -->
      <Card>
        <template #header>
          <h3 class="text-lg font-semibold">Card Component</h3>
        </template>
        <template #default>
          <p class="text-gray-600">Testing card component with padding, margins, and colors.</p>
        </template>
      </Card>
    </div>

    <!-- Original Page component -->
    <Page :app-name="name" />
  </div>
  <!-- <div class="p-4! !m-4 bg-amber-300">hello</div> -->
</template>
