<script setup lang="ts">
import { Page } from 'ui'
import { name } from './package.json'

// FIXME Cannot find name 'useHead'.ts-plugin(2304)
useHead({
  title: 'Create Turborepo (vue-nuxt:docs)',
  // FIXME eslint conflicts? Missing trailing comma.eslint@stylistic/comma-dangle
  meta: [{ name: 'description', content: 'Generated by create turbo' }]
})
</script>

<template><Page :app-name="name" /></template>
